apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- logout-fea.webcomponent.yaml
- saturn.webcomponent.yaml
- earth.webcomponent.yaml

labels:
  - pairs:
      polyfea.github.io/feature-set: polyfea-md-shell