apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: polyfea

resources:
- ../crds
- namespace.yaml
- deployment.yaml
- service.yaml
- service_account.yaml
- role.yaml
- role_binding.yaml
- leader_election_role.yaml
- leader_election_role_binding.yaml

